apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rag-manual-testing-vllm 
  janus-idp.io/tekton: rag-manual-testing-vllm
  backstage.io/kubernetes-id: rag-manual-testing-vllm
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: rag-manual-testing-vllm
resources: 
- application-dev.yaml