apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  labels: 
    app.kubernetes.io/instance: rag-manual-testing-vllm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name:  rag-manual-testing-vllm
    app.kubernetes.io/part-of: rag-manual-testing-vllm  
  name: rag-manual-testing-vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance:  rag-manual-testing-vllm 
  template:
    metadata: 
      labels:
        app.kubernetes.io/instance:  rag-manual-testing-vllm
    spec:
      containers:
      - image:  quay.io/redhat-ai-dev/ai-template-bootstrap-app:latest
        name: app-inference
        envFrom:
        - configMapRef:
            name: rag-manual-testing-vllm-model-config
        - configMapRef:
            name: rag-manual-testing-vllm-database-config
        ports:
        - containerPort: 8501
        securityContext:
          runAsNonRoot: true
