apiVersion: v1
kind: ConfigMap
metadata:
  name: rag-manual-testing-vllm-model-config
data:
  MODEL_ENDPOINT: "http://rag-manual-testing-vllm-model-server:8001"
  MODEL_NAME: "instructlab/granite-7b-lab"