apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rag-manual-testing-vllm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rag-manual-testing-vllm 
  name: rag-manual-testing-vllm
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: rag-manual-testing-vllm 
